import type { UIComponent } from "@/lib/types";
import { FACTS_FETCHED_AT } from "./helpers";

/**
 * The component-level index.
 *
 * `previewMode` decides how a component reaches the screen:
 *
 *  - "registry"  the render layer has a real implementation for it, backed by
 *                a package actually installed in the preview sandbox (Radix,
 *                Recharts, cmdk, Motion…) or by Vitrine's own registry. These
 *                are genuinely running code, not screenshots.
 *  - "compiled"  the listing ships source we compile in the sandbox at runtime.
 *  - "static"    we have not vendored the package yet, so the card links out
 *                and says so rather than pretending.
 *
 * Being explicit about the third case is deliberate: a marketplace that claims
 * everything renders and then shows a placeholder is worse than one that tells
 * you which is which.
 */

type SeedComponent = Omit<UIComponent, "_id" | "createdAt" | "views" | "saves"> & {
  createdAt?: number;
};

const raw: SeedComponent[] = [
  /* -------------------------------------------------- shadcn/ui */
  {
    listingSlug: "shadcn-ui", slug: "shadcn-button", name: "Button", kind: "button",
    description: "Six variants and four sizes over a single cva recipe, with asChild so it can become a link without losing its styling.",
    previewMode: "registry", registryKey: "shadcn/button",
    installCommand: "npx shadcn@latest add button",
    importLine: 'import { Button } from "@/components/ui/button"',
    props: [
      { name: "variant", type: "enum", options: ["default", "secondary", "outline", "ghost", "link", "destructive"], defaultValue: "default" },
      { name: "size", type: "enum", options: ["sm", "default", "lg", "icon"], defaultValue: "default" },
      { name: "disabled", type: "boolean", defaultValue: false },
    ],
    deps: ["@radix-ui/react-slot", "class-variance-authority"],
    a11yNotes: "Native button semantics; focus ring uses :focus-visible so it never fires on mouse click.",
    tags: ["cva", "asChild", "variants"], featured: true, canvasHeight: 180,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-dialog", name: "Dialog", kind: "dialog",
    description: "Modal built on Radix Dialog — focus trap, scroll lock, Escape to close, and an overlay that stays keyboard-inert.",
    previewMode: "registry", registryKey: "shadcn/dialog",
    installCommand: "npx shadcn@latest add dialog",
    importLine: 'import { Dialog, DialogContent } from "@/components/ui/dialog"',
    props: [
      { name: "size", type: "enum", options: ["sm", "default", "lg"], defaultValue: "default" },
      { name: "showClose", type: "boolean", defaultValue: true },
    ],
    deps: ["@radix-ui/react-dialog"],
    a11yNotes: "Focus is trapped and restored to the trigger on close. aria-modal and labelled title are wired for you.",
    tags: ["modal", "radix", "focus-trap"], featured: true, canvasHeight: 260,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-command", name: "Command", kind: "command",
    description: "The ⌘K palette: fuzzy filtering, grouped results, keyboard-only navigation. cmdk under the hood.",
    previewMode: "registry", registryKey: "shadcn/command",
    installCommand: "npx shadcn@latest add command",
    importLine: 'import { Command, CommandInput } from "@/components/ui/command"',
    props: [
      { name: "placeholder", type: "string", defaultValue: "Type a command or search…" },
      { name: "showGroups", type: "boolean", defaultValue: true },
    ],
    deps: ["cmdk"],
    a11yNotes: "combobox/listbox roles with aria-activedescendant; arrow keys move selection without moving DOM focus.",
    tags: ["cmdk", "palette", "search"], featured: true, canvasHeight: 320,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-tabs", name: "Tabs", kind: "tabs",
    description: "Roving-tabindex tab list with automatic activation, built on Radix Tabs.",
    previewMode: "registry", registryKey: "shadcn/tabs",
    installCommand: "npx shadcn@latest add tabs",
    importLine: 'import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"',
    props: [
      { name: "orientation", type: "enum", options: ["horizontal", "vertical"], defaultValue: "horizontal" },
      { name: "count", type: "number", defaultValue: 3 },
    ],
    deps: ["@radix-ui/react-tabs"],
    a11yNotes: "Arrow keys move between tabs, Home/End jump to ends, panels are linked with aria-controls.",
    tags: ["radix", "roving-tabindex"], featured: false, canvasHeight: 200,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-select", name: "Select", kind: "select",
    description: "Collision-aware listbox with typeahead, scroll buttons and full keyboard support.",
    previewMode: "registry", registryKey: "shadcn/select",
    installCommand: "npx shadcn@latest add select",
    importLine: 'import { Select, SelectTrigger } from "@/components/ui/select"',
    props: [
      { name: "size", type: "enum", options: ["sm", "default"], defaultValue: "default" },
      { name: "disabled", type: "boolean", defaultValue: false },
    ],
    deps: ["@radix-ui/react-select"],
    a11yNotes: "Type any letter to jump to a matching option. Selection is announced on change.",
    tags: ["radix", "listbox", "typeahead"], featured: false, canvasHeight: 200,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-toast", name: "Sonner Toast", kind: "toast",
    description: "Stacked, swipe-dismissible notifications that pause on hover and respect reduced motion.",
    previewMode: "registry", registryKey: "shadcn/toast",
    installCommand: "npx shadcn@latest add sonner",
    importLine: 'import { toast } from "sonner"',
    props: [
      { name: "variant", type: "enum", options: ["default", "success", "error", "warning"], defaultValue: "success" },
      { name: "withAction", type: "boolean", defaultValue: true },
    ],
    deps: ["sonner"],
    a11yNotes: "Rendered into an aria-live region so screen readers announce without stealing focus.",
    tags: ["sonner", "notifications"], featured: false, canvasHeight: 200,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-form", name: "Form Field", kind: "form",
    description: "React Hook Form + Zod wired to labels, descriptions and error messages with the aria plumbing already correct.",
    previewMode: "registry", registryKey: "shadcn/form",
    installCommand: "npx shadcn@latest add form",
    importLine: 'import { Form, FormField } from "@/components/ui/form"',
    props: [
      { name: "showError", type: "boolean", defaultValue: false },
      { name: "layout", type: "enum", options: ["stacked", "inline"], defaultValue: "stacked" },
    ],
    deps: ["react-hook-form", "zod", "@hookform/resolvers"],
    a11yNotes: "aria-invalid and aria-describedby are derived from validation state, so errors are announced.",
    tags: ["react-hook-form", "zod", "validation"], featured: true, canvasHeight: 280,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-data-table", name: "Data Table", kind: "data-grid",
    description: "TanStack Table wired to shadcn primitives: sorting, column visibility, row selection and pagination.",
    previewMode: "registry", registryKey: "shadcn/data-table",
    installCommand: "npx shadcn@latest add table",
    importLine: 'import { DataTable } from "@/components/data-table"',
    props: [
      { name: "rows", type: "number", defaultValue: 6 },
      { name: "selectable", type: "boolean", defaultValue: true },
      { name: "density", type: "enum", options: ["comfortable", "compact"], defaultValue: "comfortable" },
    ],
    deps: ["@tanstack/react-table"],
    a11yNotes: "Real table semantics with scope on headers; sort state exposed via aria-sort.",
    tags: ["tanstack", "sorting", "selection"], featured: true, canvasHeight: 380,
  },

  /* -------------------------------------------------- Radix */
  {
    listingSlug: "radix-primitives", slug: "radix-tooltip", name: "Tooltip", kind: "tooltip",
    description: "Hover and focus triggered, collision aware, with a shared delay so a row of them doesn't flicker.",
    previewMode: "registry", registryKey: "radix/tooltip",
    installCommand: "npm i @radix-ui/react-tooltip",
    importLine: 'import * as Tooltip from "@radix-ui/react-tooltip"',
    props: [
      { name: "side", type: "enum", options: ["top", "right", "bottom", "left"], defaultValue: "top" },
      { name: "delayDuration", type: "number", defaultValue: 200 },
    ],
    deps: ["@radix-ui/react-tooltip"],
    a11yNotes: "Opens on keyboard focus as well as hover, and never traps a pointer-only user.",
    tags: ["overlay", "positioning"], featured: false, canvasHeight: 180,
  },
  {
    listingSlug: "radix-primitives", slug: "radix-accordion", name: "Accordion", kind: "accordion",
    description: "Single or multiple expansion with CSS-variable height animation that works without measuring in JS.",
    previewMode: "registry", registryKey: "radix/accordion",
    installCommand: "npm i @radix-ui/react-accordion",
    importLine: 'import * as Accordion from "@radix-ui/react-accordion"',
    props: [
      { name: "type", type: "enum", options: ["single", "multiple"], defaultValue: "single" },
      { name: "collapsible", type: "boolean", defaultValue: true },
    ],
    deps: ["@radix-ui/react-accordion"],
    a11yNotes: "Headers are real buttons inside heading elements; aria-expanded and aria-controls are managed.",
    tags: ["disclosure", "radix"], featured: false, canvasHeight: 280,
  },
  {
    listingSlug: "radix-primitives", slug: "radix-dropdown", name: "Dropdown Menu", kind: "dropdown",
    description: "Nested submenus, checkbox and radio items, typeahead, and pointer-intent handling that forgives diagonal mouse paths.",
    previewMode: "registry", registryKey: "radix/dropdown",
    installCommand: "npm i @radix-ui/react-dropdown-menu",
    importLine: 'import * as DropdownMenu from "@radix-ui/react-dropdown-menu"',
    props: [
      { name: "align", type: "enum", options: ["start", "center", "end"], defaultValue: "start" },
      { name: "withCheckboxes", type: "boolean", defaultValue: true },
    ],
    deps: ["@radix-ui/react-dropdown-menu"],
    a11yNotes: "menu/menuitem roles, arrow-key navigation, Escape closes and returns focus to the trigger.",
    tags: ["menu", "radix", "submenu"], featured: false, canvasHeight: 240,
  },
  {
    listingSlug: "radix-primitives", slug: "radix-slider", name: "Slider", kind: "slider",
    description: "Single or range thumbs, step and min-steps-between-thumbs, RTL aware.",
    previewMode: "registry", registryKey: "radix/slider",
    installCommand: "npm i @radix-ui/react-slider",
    importLine: 'import * as Slider from "@radix-ui/react-slider"',
    props: [
      { name: "range", type: "boolean", defaultValue: false },
      { name: "step", type: "number", defaultValue: 1 },
    ],
    deps: ["@radix-ui/react-slider"],
    a11yNotes: "Arrow keys step, Page keys jump, Home/End go to bounds; value announced via aria-valuenow.",
    tags: ["input", "range"], featured: false, canvasHeight: 160,
  },
  {
    listingSlug: "radix-primitives", slug: "radix-switch", name: "Switch", kind: "switch",
    description: "A two-state toggle with correct role and a thumb transition that respects prefers-reduced-motion.",
    previewMode: "registry", registryKey: "radix/switch",
    installCommand: "npm i @radix-ui/react-switch",
    importLine: 'import * as Switch from "@radix-ui/react-switch"',
    props: [
      { name: "checked", type: "boolean", defaultValue: true },
      { name: "disabled", type: "boolean", defaultValue: false },
    ],
    deps: ["@radix-ui/react-switch"],
    a11yNotes: "role=switch with aria-checked — announced as on/off rather than as a checkbox.",
    tags: ["toggle", "form"], featured: false, canvasHeight: 140,
  },

  /* -------------------------------------------------- Recharts / Tremor */
  {
    listingSlug: "recharts", slug: "recharts-area", name: "Area Chart", kind: "chart",
    description: "Gradient-filled area chart with a responsive container, custom tooltip and theme-aware stroke.",
    previewMode: "registry", registryKey: "recharts/area",
    installCommand: "npm i recharts",
    importLine: 'import { AreaChart, Area } from "recharts"',
    props: [
      { name: "curve", type: "enum", options: ["monotone", "linear", "step"], defaultValue: "monotone" },
      { name: "showGrid", type: "boolean", defaultValue: true },
      { name: "stacked", type: "boolean", defaultValue: false },
    ],
    deps: ["recharts"],
    a11yNotes: "SVG chart — pair with a visually hidden data table for screen reader users.",
    tags: ["chart", "svg", "responsive"], featured: true, canvasHeight: 300, gridBackdrop: true,
  },
  {
    listingSlug: "recharts", slug: "recharts-bar", name: "Bar Chart", kind: "chart",
    description: "Grouped or stacked bars with rounded caps and a legend that toggles series.",
    previewMode: "registry", registryKey: "recharts/bar",
    installCommand: "npm i recharts",
    importLine: 'import { BarChart, Bar } from "recharts"',
    props: [
      { name: "stacked", type: "boolean", defaultValue: false },
      { name: "horizontal", type: "boolean", defaultValue: false },
    ],
    deps: ["recharts"],
    tags: ["chart", "bars"], featured: false, canvasHeight: 300, gridBackdrop: true,
  },
  {
    listingSlug: "tremor", slug: "tremor-kpi-card", name: "KPI Card", kind: "stat",
    description: "Metric, delta badge and inline sparkline in the density analytics dashboards actually need.",
    previewMode: "registry", registryKey: "tremor/kpi",
    installCommand: "npm i @tremor/react",
    importLine: 'import { Card, Metric } from "@tremor/react"',
    props: [
      { name: "trend", type: "enum", options: ["up", "down", "flat"], defaultValue: "up" },
      { name: "showSparkline", type: "boolean", defaultValue: true },
    ],
    deps: ["recharts"],
    tags: ["dashboard", "metric", "sparkline"], featured: true, canvasHeight: 200,
  },
  {
    listingSlug: "tremor", slug: "tremor-sparkline", name: "Sparkline", kind: "sparkline",
    description: "Axis-free trend line sized to sit inline in a table cell or a stat card.",
    previewMode: "registry", registryKey: "tremor/sparkline",
    installCommand: "npm i @tremor/react",
    importLine: 'import { SparkAreaChart } from "@tremor/react"',
    props: [
      { name: "variant", type: "enum", options: ["area", "line", "bars"], defaultValue: "area" },
      { name: "points", type: "number", defaultValue: 24 },
    ],
    deps: ["recharts"],
    tags: ["inline", "trend"], featured: false, canvasHeight: 140,
  },

  /* -------------------------------------------------- Motion / effects */
  {
    listingSlug: "motion", slug: "motion-layout-list", name: "Layout Animated List", kind: "list",
    description: "Reorderable list where every item animates to its new position via the layout prop — no FLIP maths by hand.",
    previewMode: "registry", registryKey: "motion/layout-list",
    installCommand: "npm i motion",
    importLine: 'import { motion, AnimatePresence } from "motion/react"',
    props: [
      { name: "items", type: "number", defaultValue: 5 },
      { name: "spring", type: "enum", options: ["gentle", "snappy", "bouncy"], defaultValue: "snappy" },
    ],
    deps: ["motion"],
    a11yNotes: "Animation is suppressed entirely under prefers-reduced-motion rather than merely shortened.",
    tags: ["layout", "flip", "reorder"], featured: true, canvasHeight: 320,
  },
  {
    listingSlug: "motion", slug: "motion-shared-element", name: "Shared Element Transition", kind: "carousel",
    description: "A card that expands into a detail view with layoutId, keeping the same DOM node throughout.",
    previewMode: "registry", registryKey: "motion/shared-element",
    installCommand: "npm i motion",
    importLine: 'import { motion } from "motion/react"',
    props: [{ name: "duration", type: "number", defaultValue: 0.4 }],
    deps: ["motion"],
    tags: ["layoutId", "transition"], featured: false, canvasHeight: 340,
  },
  {
    listingSlug: "magic-ui", slug: "magic-marquee", name: "Marquee", kind: "marquee",
    description: "Infinite CSS-driven scroller with edge fades and pause-on-hover. No JS ticking per frame.",
    previewMode: "registry", registryKey: "magic/marquee",
    installCommand: "npx shadcn@latest add \"https://magicui.design/r/marquee\"",
    importLine: 'import { Marquee } from "@/components/ui/marquee"',
    props: [
      { name: "direction", type: "enum", options: ["left", "right"], defaultValue: "left" },
      { name: "speed", type: "enum", options: ["slow", "normal", "fast"], defaultValue: "normal" },
      { name: "pauseOnHover", type: "boolean", defaultValue: true },
    ],
    deps: [],
    a11yNotes: "Motion stops under prefers-reduced-motion; content stays in the accessibility tree either way.",
    tags: ["logos", "css-animation", "infinite"], featured: true, canvasHeight: 180,
  },
  {
    listingSlug: "magic-ui", slug: "magic-number-ticker", name: "Number Ticker", kind: "stat",
    description: "Counts a number up when it scrolls into view, with locale-aware formatting.",
    previewMode: "registry", registryKey: "magic/number-ticker",
    installCommand: "npx shadcn@latest add \"https://magicui.design/r/number-ticker\"",
    importLine: 'import { NumberTicker } from "@/components/ui/number-ticker"',
    props: [
      { name: "value", type: "number", defaultValue: 12480 },
      { name: "decimals", type: "number", defaultValue: 0 },
    ],
    deps: ["motion"],
    a11yNotes: "The final value is rendered for assistive tech immediately; only the visual count animates.",
    tags: ["counter", "scroll", "stats"], featured: false, canvasHeight: 160,
  },
  {
    listingSlug: "magic-ui", slug: "magic-animated-grid", name: "Animated Grid Pattern", kind: "background",
    description: "A grid backdrop where cells light up on a randomised schedule. Pure CSS and SVG.",
    previewMode: "registry", registryKey: "magic/grid-pattern",
    installCommand: "npx shadcn@latest add \"https://magicui.design/r/animated-grid-pattern\"",
    importLine: 'import { AnimatedGridPattern } from "@/components/ui/animated-grid-pattern"',
    props: [
      { name: "density", type: "enum", options: ["sparse", "normal", "dense"], defaultValue: "normal" },
      { name: "animate", type: "boolean", defaultValue: true },
    ],
    deps: ["motion"],
    tags: ["background", "svg", "decorative"], featured: false, canvasHeight: 260,
  },
  {
    listingSlug: "motion-primitives", slug: "mp-text-shimmer", name: "Text Shimmer", kind: "text-effect",
    description: "A moving highlight across text, used for streaming or loading states. background-clip, not an overlay.",
    previewMode: "registry", registryKey: "mp/text-shimmer",
    installCommand: "npx motion-primitives@latest add text-shimmer",
    importLine: 'import { TextShimmer } from "@/components/ui/text-shimmer"',
    props: [
      { name: "duration", type: "number", defaultValue: 2 },
      { name: "size", type: "enum", options: ["sm", "base", "lg", "xl"], defaultValue: "lg" },
    ],
    deps: ["motion"],
    tags: ["loading", "streaming", "text"], featured: true, canvasHeight: 140,
  },
  {
    listingSlug: "motion-primitives", slug: "mp-animated-cursor", name: "Animated Cursor", kind: "cursor",
    description: "A follower cursor that morphs over interactive targets, with a spring that settles rather than snaps.",
    previewMode: "registry", registryKey: "mp/cursor",
    installCommand: "npx motion-primitives@latest add cursor",
    importLine: 'import { Cursor } from "@/components/ui/cursor"',
    props: [{ name: "variant", type: "enum", options: ["dot", "ring", "label"], defaultValue: "ring" }],
    deps: ["motion"],
    a11yNotes: "Decorative only — hidden from assistive tech and disabled on touch input.",
    tags: ["pointer", "micro-interaction"], featured: false, canvasHeight: 240,
  },

  /* -------------------------------------------------- cmdk / sonner / forms */
  {
    listingSlug: "shadcn-ui", slug: "shadcn-combobox", name: "Combobox", kind: "combobox",
    description: "Popover plus command list: filterable, keyboard-first, and it clears properly on Escape.",
    previewMode: "registry", registryKey: "shadcn/combobox",
    installCommand: "npx shadcn@latest add combobox",
    importLine: 'import { Combobox } from "@/components/ui/combobox"',
    props: [
      { name: "multiple", type: "boolean", defaultValue: false },
      { name: "placeholder", type: "string", defaultValue: "Select framework…" },
    ],
    deps: ["cmdk", "@radix-ui/react-popover"],
    a11yNotes: "aria-expanded on the trigger and aria-selected on options; focus stays in the input while arrowing.",
    tags: ["autocomplete", "cmdk"], featured: false, canvasHeight: 300,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-input-otp", name: "OTP Field", kind: "otp",
    description: "Six single-character inputs that behave as one field: paste fills them all, backspace walks back.",
    previewMode: "registry", registryKey: "shadcn/input-otp",
    installCommand: "npx shadcn@latest add input-otp",
    importLine: 'import { InputOTP } from "@/components/ui/input-otp"',
    props: [
      { name: "length", type: "number", defaultValue: 6 },
      { name: "state", type: "enum", options: ["idle", "error", "success"], defaultValue: "idle" },
    ],
    deps: ["input-otp"],
    a11yNotes: "Presented as a single labelled group with one-time-code autocomplete so password managers cooperate.",
    tags: ["auth", "input", "paste"], featured: false, canvasHeight: 180,
  },

  /* -------------------------------------------------- Static (not vendored yet) */
  {
    listingSlug: "mantine", slug: "mantine-date-picker", name: "Date Picker", kind: "date-picker",
    description: "Range selection, presets, min/max bounds and locale support out of the box.",
    previewMode: "static",
    installCommand: "npm i @mantine/dates",
    importLine: 'import { DatePicker } from "@mantine/dates"',
    props: [], deps: ["@mantine/dates", "dayjs"],
    tags: ["dates", "range"], featured: false,
  },
  {
    listingSlug: "mantine", slug: "mantine-rich-text", name: "Rich Text Editor", kind: "editor",
    description: "Tiptap wrapped with a working toolbar, bubble menu and paste handling.",
    previewMode: "static",
    installCommand: "npm i @mantine/tiptap",
    importLine: 'import { RichTextEditor } from "@mantine/tiptap"',
    props: [], deps: ["@mantine/tiptap", "@tiptap/react"],
    tags: ["tiptap", "wysiwyg"], featured: false,
  },
  {
    listingSlug: "ag-grid", slug: "ag-grid-virtual", name: "Virtualised Grid", kind: "data-grid",
    description: "Row and column virtualisation that stays smooth past a million rows.",
    previewMode: "static",
    installCommand: "npm i ag-grid-react ag-grid-community",
    importLine: 'import { AgGridReact } from "ag-grid-react"',
    props: [], deps: ["ag-grid-community"],
    tags: ["virtualisation", "enterprise"], featured: false,
  },
  {
    listingSlug: "heroui", slug: "heroui-autocomplete", name: "Autocomplete", kind: "combobox",
    description: "Async loading, sections and virtualisation, over React Aria's combobox behaviour.",
    previewMode: "static",
    installCommand: "npm i @heroui/autocomplete",
    importLine: 'import { Autocomplete } from "@heroui/react"',
    props: [], deps: ["@heroui/react"],
    tags: ["react-aria", "async"], featured: false,
  },
  {
    listingSlug: "chakra-ui", slug: "chakra-toast", name: "Toaster", kind: "toast",
    description: "Placement-aware toasts with promise helpers and pause-on-interaction.",
    previewMode: "static",
    installCommand: "npm i @chakra-ui/react",
    importLine: 'import { toaster } from "@/components/ui/toaster"',
    props: [], deps: ["@chakra-ui/react"],
    tags: ["notifications"], featured: false,
  },
  {
    listingSlug: "wcag-patterns", slug: "apg-combobox-pattern", name: "Combobox Pattern", kind: "combobox",
    description: "The reference keyboard map and ARIA wiring every combobox implementation is measured against.",
    previewMode: "static",
    props: [], deps: [],
    a11yNotes: "Defines the expected behaviour for Escape, Alt+Down, Home/End and aria-activedescendant.",
    tags: ["reference", "wai-aria", "keyboard"], featured: false,
  },

  /* -------------------------------------------------- shadcn/ui, continued */
  {
    listingSlug: "shadcn-ui", slug: "shadcn-card", name: "Card", kind: "card",
    description: "Header, content and footer slots with the border and shadow already tuned for both themes.",
    previewMode: "registry", registryKey: "shadcn/card",
    installCommand: "npx shadcn@latest add card",
    importLine: 'import { Card, CardHeader } from "@/components/ui/card"',
    props: [
      { name: "withFooter", type: "boolean", defaultValue: true },
      { name: "withImage", type: "boolean", defaultValue: false },
    ],
    deps: [], tags: ["surface", "layout"], featured: false, canvasHeight: 260,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-badge", name: "Badge", kind: "badge",
    description: "Four variants at a size that sits on a baseline with 13px text without knocking the line box around.",
    previewMode: "registry", registryKey: "shadcn/badge",
    installCommand: "npx shadcn@latest add badge",
    importLine: 'import { Badge } from "@/components/ui/badge"',
    props: [
      { name: "variant", type: "enum", options: ["default", "secondary", "outline", "destructive"], defaultValue: "default" },
    ],
    deps: ["class-variance-authority"], tags: ["chip", "status"], featured: false, canvasHeight: 140,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-avatar", name: "Avatar", kind: "avatar",
    description: "Image with an initials fallback that only appears after the image genuinely fails, not before it loads.",
    previewMode: "registry", registryKey: "shadcn/avatar",
    installCommand: "npx shadcn@latest add avatar",
    importLine: 'import { Avatar, AvatarImage } from "@/components/ui/avatar"',
    props: [
      { name: "size", type: "enum", options: ["sm", "default", "lg"], defaultValue: "default" },
      { name: "stack", type: "boolean", defaultValue: false },
    ],
    deps: ["@radix-ui/react-avatar"],
    a11yNotes: "The fallback carries the person's initials as text, so it is never an unlabelled coloured circle.",
    tags: ["identity", "radix"], featured: false, canvasHeight: 160,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-progress", name: "Progress", kind: "progress",
    description: "Determinate bar driven by a transform, so it animates on the compositor rather than by width.",
    previewMode: "registry", registryKey: "shadcn/progress",
    installCommand: "npx shadcn@latest add progress",
    importLine: 'import { Progress } from "@/components/ui/progress"',
    props: [
      { name: "value", type: "number", defaultValue: 62 },
      { name: "indeterminate", type: "boolean", defaultValue: false },
    ],
    deps: ["@radix-ui/react-progress"],
    a11yNotes: "role=progressbar with aria-valuenow, so the percentage is announced rather than only drawn.",
    tags: ["feedback", "radix"], featured: false, canvasHeight: 140,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-checkbox", name: "Checkbox", kind: "checkbox",
    description: "Checked, unchecked and indeterminate, with a hit area larger than the box it draws.",
    previewMode: "registry", registryKey: "shadcn/checkbox",
    installCommand: "npx shadcn@latest add checkbox",
    importLine: 'import { Checkbox } from "@/components/ui/checkbox"',
    props: [
      { name: "state", type: "enum", options: ["unchecked", "checked", "indeterminate"], defaultValue: "checked" },
      { name: "withLabel", type: "boolean", defaultValue: true },
    ],
    deps: ["@radix-ui/react-checkbox"], tags: ["form", "radix"], featured: false, canvasHeight: 160,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-radio-group", name: "Radio Group", kind: "radio",
    description: "One choice from several, with roving tabindex so the whole group is a single tab stop.",
    previewMode: "registry", registryKey: "shadcn/radio-group",
    installCommand: "npx shadcn@latest add radio-group",
    importLine: 'import { RadioGroup } from "@/components/ui/radio-group"',
    props: [
      { name: "orientation", type: "enum", options: ["vertical", "horizontal"], defaultValue: "vertical" },
      { name: "asCards", type: "boolean", defaultValue: false },
    ],
    deps: ["@radix-ui/react-radio-group"],
    a11yNotes: "Arrow keys move and select in one step, which is the expected radio behaviour.",
    tags: ["form", "radix"], featured: false, canvasHeight: 200,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-hover-card", name: "Hover Card", kind: "popover",
    description: "Rich preview on hover with open and close delays that stop it firing on a passing cursor.",
    previewMode: "registry", registryKey: "shadcn/hover-card",
    installCommand: "npx shadcn@latest add hover-card",
    importLine: 'import { HoverCard } from "@/components/ui/hover-card"',
    props: [
      { name: "openDelay", type: "number", defaultValue: 300 },
      { name: "side", type: "enum", options: ["top", "right", "bottom", "left"], defaultValue: "bottom" },
    ],
    deps: ["@radix-ui/react-hover-card"],
    a11yNotes: "Hover-only by design — pair it with a link or button that carries the same information.",
    tags: ["overlay", "preview"], featured: false, canvasHeight: 240,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-collapsible", name: "Collapsible", kind: "accordion",
    description: "A single disclosure with animated height, for the cases an accordion would be overkill.",
    previewMode: "registry", registryKey: "shadcn/collapsible",
    installCommand: "npx shadcn@latest add collapsible",
    importLine: 'import { Collapsible } from "@/components/ui/collapsible"',
    props: [{ name: "defaultOpen", type: "boolean", defaultValue: false }],
    deps: ["@radix-ui/react-collapsible"], tags: ["disclosure", "radix"], featured: false, canvasHeight: 200,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-context-menu", name: "Context Menu", kind: "context-menu",
    description: "Right-click menu with submenus, checkbox items and shortcut hints, keyboard reachable too.",
    previewMode: "registry", registryKey: "shadcn/context-menu",
    installCommand: "npx shadcn@latest add context-menu",
    importLine: 'import { ContextMenu } from "@/components/ui/context-menu"',
    props: [{ name: "withSubmenu", type: "boolean", defaultValue: true }],
    deps: ["@radix-ui/react-context-menu"],
    a11yNotes: "Opens on the context-menu key as well as right click, so it is not mouse-only.",
    tags: ["menu", "radix"], featured: false, canvasHeight: 240,
  },
  {
    listingSlug: "shadcn-ui", slug: "shadcn-toggle-group", name: "Toggle Group", kind: "tabs",
    description: "Segmented control in single or multiple mode, sized to sit next to a 32px button.",
    previewMode: "registry", registryKey: "shadcn/toggle-group",
    installCommand: "npx shadcn@latest add toggle-group",
    importLine: 'import { ToggleGroup } from "@/components/ui/toggle-group"',
    props: [
      { name: "type", type: "enum", options: ["single", "multiple"], defaultValue: "single" },
      { name: "size", type: "enum", options: ["sm", "default"], defaultValue: "default" },
    ],
    deps: ["@radix-ui/react-toggle-group"], tags: ["segmented", "radix"], featured: false, canvasHeight: 150,
  },

  /* -------------------------------------------------- Recharts, continued */
  {
    listingSlug: "recharts", slug: "recharts-line", name: "Line Chart", kind: "chart",
    description: "Multi-series lines with an active dot and a tooltip that follows the nearest point, not the cursor.",
    previewMode: "registry", registryKey: "recharts/line",
    installCommand: "npm i recharts",
    importLine: 'import { LineChart, Line } from "recharts"',
    props: [
      { name: "series", type: "number", defaultValue: 2 },
      { name: "dots", type: "boolean", defaultValue: false },
    ],
    deps: ["recharts"], tags: ["chart", "trend"], featured: false, canvasHeight: 300, gridBackdrop: true,
  },
  {
    listingSlug: "recharts", slug: "recharts-pie", name: "Donut Chart", kind: "chart",
    description: "Donut with a centre label, padding angle and a legend that survives long category names.",
    previewMode: "registry", registryKey: "recharts/pie",
    installCommand: "npm i recharts",
    importLine: 'import { PieChart, Pie } from "recharts"',
    props: [
      { name: "innerRadius", type: "number", defaultValue: 60 },
      { name: "showLabel", type: "boolean", defaultValue: true },
    ],
    deps: ["recharts"], tags: ["chart", "proportion"], featured: false, canvasHeight: 300,
  },
  {
    listingSlug: "recharts", slug: "recharts-radial", name: "Radial Bar", kind: "chart",
    description: "Radial progress rings for bounded metrics — the shape dashboards reach for and usually hand-roll.",
    previewMode: "registry", registryKey: "recharts/radial",
    installCommand: "npm i recharts",
    importLine: 'import { RadialBarChart } from "recharts"',
    props: [{ name: "value", type: "number", defaultValue: 72 }],
    deps: ["recharts"], tags: ["chart", "gauge"], featured: false, canvasHeight: 280,
  },

  /* -------------------------------------------------- Static (not vendored) */
  {
    listingSlug: "magic-ui", slug: "magic-bento-grid", name: "Bento Grid", kind: "feature-grid",
    description: "Asymmetric feature grid with hover reveal, the layout every launch page used in 2024 and still works.",
    previewMode: "static",
    installCommand: "npx shadcn@latest add \"https://magicui.design/r/bento-grid\"",
    importLine: 'import { BentoGrid } from "@/components/ui/bento-grid"',
    props: [], deps: ["motion"], tags: ["layout", "marketing"], featured: false,
  },
  {
    listingSlug: "magic-ui", slug: "magic-border-beam", name: "Border Beam", kind: "background",
    description: "A light travelling around a card's border, done with a conic gradient and one animated offset.",
    previewMode: "static",
    installCommand: "npx shadcn@latest add \"https://magicui.design/r/border-beam\"",
    importLine: 'import { BorderBeam } from "@/components/ui/border-beam"',
    props: [], deps: ["motion"], tags: ["decorative", "card"], featured: false,
  },
  {
    listingSlug: "aceternity-ui", slug: "aceternity-aurora", name: "Aurora Background", kind: "background",
    description: "Slow-moving gradient wash behind hero copy. Heavy on paint; use it once per page.",
    previewMode: "static",
    installCommand: "npx shadcn@latest add \"https://ui.aceternity.com/registry/aurora-background.json\"",
    importLine: 'import { AuroraBackground } from "@/components/ui/aurora-background"',
    props: [], deps: ["motion"], tags: ["hero", "gradient"], featured: false,
  },
  {
    listingSlug: "ark-ui", slug: "ark-date-picker", name: "Date Picker", kind: "date-picker",
    description: "Single, multiple and range selection driven by a Zag state machine, identical across four frameworks.",
    previewMode: "static",
    installCommand: "npm i @ark-ui/react",
    importLine: 'import { DatePicker } from "@ark-ui/react/date-picker"',
    props: [], deps: ["@ark-ui/react"],
    a11yNotes: "Grid semantics with aria-selected per day and full arrow-key navigation across weeks and months.",
    tags: ["dates", "zag", "cross-framework"], featured: false,
  },
  {
    listingSlug: "base-ui", slug: "base-number-field", name: "Number Field", kind: "input",
    description: "Numeric input with scrub-to-change, locale formatting and clamped min/max.",
    previewMode: "static",
    installCommand: "npm i @base-ui-components/react",
    importLine: 'import { NumberField } from "@base-ui-components/react/number-field"',
    props: [], deps: ["@base-ui-components/react"],
    a11yNotes: "role=spinbutton with aria-valuenow/min/max, and the increment buttons stay keyboard reachable.",
    tags: ["form", "numeric"], featured: false,
  },
  {
    listingSlug: "daisyui", slug: "daisy-chat-bubble", name: "Chat Bubble", kind: "chat",
    description: "Message bubbles with avatar, header, footer and side, in pure CSS classes and no JavaScript at all.",
    previewMode: "static",
    installCommand: "npm i -D daisyui",
    importLine: '<div class="chat chat-start">…</div>',
    props: [], deps: [], tags: ["chat", "css-only"], featured: false,
  },
  {
    listingSlug: "mantine", slug: "mantine-spotlight", name: "Spotlight", kind: "command",
    description: "Mantine's command palette with action groups, custom filtering and a keyboard shortcut hook.",
    previewMode: "static",
    installCommand: "npm i @mantine/spotlight",
    importLine: 'import { Spotlight } from "@mantine/spotlight"',
    props: [], deps: ["@mantine/spotlight"], tags: ["palette", "search"], featured: false,
  },
  {
    listingSlug: "tremor", slug: "tremor-bar-list", name: "Bar List", kind: "list",
    description: "Ranked rows with an inline proportional bar — the densest way to show a top-ten.",
    previewMode: "static",
    installCommand: "npm i @tremor/react",
    importLine: 'import { BarList } from "@tremor/react"',
    props: [], deps: [], tags: ["dashboard", "ranking"], featured: false,
  },
];

export const seedComponents: UIComponent[] = raw.map((c) => ({
  ...c,
  _id: `component:${c.slug}`,
  createdAt: c.createdAt ?? FACTS_FETCHED_AT,
  views: 0,
  saves: 0,
}));
