import type { Listing } from "@/lib/types";
import { hydrate, stack, type SeedListing } from "./helpers";

const raw: SeedListing[] = [
  /* ======================================================================
     UI LIBRARIES & DESIGN SYSTEMS
     ====================================================================== */
  {
    kind: "library",
    slug: "shadcn-ui",
    name: "shadcn/ui",
    tagline: "Copy-paste components you own outright",
    description:
      "Not a dependency — a set of accessible components built on Radix primitives and Tailwind that you copy into your own repo via a CLI. You own the source, so you can edit anything without fighting a package boundary. The pattern that reset how the React ecosystem ships UI.",
    categories: ["component-libraries", "design-systems", "headless-primitives"],
    tags: ["radix", "tailwind", "cli", "registry", "copy-paste"],
    homepage: "https://ui.shadcn.com",
    repo: "https://github.com/shadcn-ui/ui",
    docs: "https://ui.shadcn.com/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "remix", "vite", "astro"],
      styling: ["tailwind-4", "tailwind-3"],
      rsc: "mixed",
      a11y: "audited",
      install: ["cli", "copy-paste"],
    }),
    color: "#0b0b0f",
    monogram: "SH",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "radix-primitives",
    name: "Radix Primitives",
    tagline: "Unstyled, accessible behaviour for the hard components",
    description:
      "The behaviour layer most modern React UI is built on. Focus management, typeahead, collision-aware positioning and WAI-ARIA conformance, with zero opinions about how anything looks. If a component has a keyboard interaction you keep getting wrong, Radix has already solved it.",
    categories: ["headless-primitives", "component-libraries", "accessibility"],
    tags: ["headless", "accessible", "wai-aria", "unstyled"],
    homepage: "https://www.radix-ui.com/primitives",
    repo: "https://github.com/radix-ui/primitives",
    npm: "@radix-ui/react-dialog",
    docs: "https://www.radix-ui.com/primitives/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "remix", "vite"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "audited",
    }),
    color: "#6e56cf",
    monogram: "RX",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "base-ui",
    name: "Base UI",
    tagline: "Headless primitives from the MUI and Radix teams",
    description:
      "A ground-up rewrite of the unstyled-primitive idea by people who have shipped two generations of it. Smaller surface than Radix, stricter about composition, and designed for React 19 from the start rather than migrated to it.",
    categories: ["headless-primitives", "component-libraries", "accessibility"],
    tags: ["headless", "unstyled", "react-19", "accessible"],
    homepage: "https://base-ui.com",
    repo: "https://github.com/mui/base-ui",
    npm: "@base-ui-components/react",
    docs: "https://base-ui.com/react/overview/quick-start",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vite"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "audited",
    }),
    color: "#0a5cff",
    monogram: "BU",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "ark-ui",
    name: "Ark UI",
    tagline: "State-machine primitives that work in four frameworks",
    description:
      "Headless components built on Zag.js state machines, so the same interaction logic ships to React, Vue, Solid and Svelte with identical behaviour. Worth it if you maintain UI across more than one framework and are tired of the drift.",
    categories: ["headless-primitives", "component-libraries", "design-systems"],
    tags: ["headless", "zag", "cross-framework", "state-machines"],
    homepage: "https://ark-ui.com",
    repo: "https://github.com/chakra-ui/ark",
    npm: "@ark-ui/react",
    docs: "https://ark-ui.com/docs/overview/introduction",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "vue", "solid", "svelte", "next"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "audited",
    }),
    color: "#7c3aed",
    monogram: "AK",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "mantine",
    name: "Mantine",
    tagline: "120+ components and 70+ hooks, batteries included",
    description:
      "One of the few libraries that covers the boring end of the spectrum properly — rich text editor, date pickers, carousels, notifications, form state — without you assembling six packages. Dark mode and theming are first-class rather than bolted on.",
    categories: ["component-libraries", "design-systems", "forms-inputs"],
    tags: ["hooks", "theming", "forms", "dates"],
    homepage: "https://mantine.dev",
    repo: "https://github.com/mantinedev/mantine",
    npm: "@mantine/core",
    docs: "https://mantine.dev/getting-started",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vite", "remix"],
      styling: ["css-modules"],
      rsc: "client",
      a11y: "partial",
    }),
    color: "#339af0",
    monogram: "MT",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "chakra-ui",
    name: "Chakra UI",
    tagline: "Accessible components with a strong style-props system",
    description:
      "Composable components with an ergonomic style-prop API and a serious commitment to accessibility. Version 3 moved onto Panda CSS and Ark, which cut runtime cost significantly compared with the emotion-era releases.",
    categories: ["component-libraries", "design-systems", "css-styling"],
    tags: ["style-props", "theming", "panda", "accessible"],
    homepage: "https://chakra-ui.com",
    repo: "https://github.com/chakra-ui/chakra-ui",
    npm: "@chakra-ui/react",
    docs: "https://chakra-ui.com/docs/get-started",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vite", "remix"],
      styling: ["css-in-js"],
      rsc: "client",
      a11y: "audited",
    }),
    color: "#3ab6b0",
    monogram: "CH",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "mui",
    name: "MUI",
    tagline: "Material Design for React, at enterprise scale",
    description:
      "The most complete React component library by surface area, with a paid X tier covering data grids, date pickers and charts. Heavy, opinionated, and unmatched if you need something that already exists and is already supported.",
    categories: ["component-libraries", "design-systems", "tables-grids"],
    tags: ["material", "enterprise", "data-grid", "theming"],
    homepage: "https://mui.com",
    repo: "https://github.com/mui/material-ui",
    npm: "@mui/material",
    docs: "https://mui.com/material-ui/getting-started",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "freemium",
    priceNote: "Core is MIT; MUI X Pro from $180/dev/yr",
    stack: stack({
      frameworks: ["react", "next", "vite", "remix"],
      styling: ["css-in-js"],
      rsc: "mixed",
      a11y: "audited",
    }),
    color: "#007fff",
    monogram: "MU",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "heroui",
    name: "HeroUI",
    tagline: "Beautiful defaults on top of React Aria",
    description:
      "Styled components built over React Aria's behaviour layer and Tailwind Variants, so the accessibility work is inherited rather than reimplemented. Looks good out of the box, which is rarer than it should be for an a11y-first library.",
    categories: ["component-libraries", "design-systems"],
    tags: ["react-aria", "tailwind-variants", "themeable"],
    homepage: "https://www.heroui.com",
    repo: "https://github.com/heroui-inc/heroui",
    npm: "@heroui/react",
    docs: "https://www.heroui.com/docs/guide/introduction",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vite"],
      styling: ["tailwind-4", "tailwind-3"],
      rsc: "client",
      a11y: "audited",
    }),
    color: "#006fee",
    monogram: "HR",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "react-aria",
    name: "React Aria",
    tagline: "Adobe's behaviour and a11y hooks, no styling attached",
    description:
      "Hooks that implement adaptive interactions for 50+ patterns, tested against real assistive technology across desktop, mobile and touch. The most rigorous accessibility work available in React, and correspondingly low-level.",
    categories: ["headless-primitives", "accessibility", "component-libraries"],
    tags: ["adobe", "hooks", "i18n", "wai-aria"],
    homepage: "https://react-spectrum.adobe.com/react-aria",
    repo: "https://github.com/adobe/react-spectrum",
    npm: "react-aria-components",
    docs: "https://react-spectrum.adobe.com/react-aria/getting-started.html",
    license: "Apache-2.0",
    licenseBucket: "apache-2.0",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vite", "remix"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "audited",
    }),
    color: "#e34850",
    monogram: "RA",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "daisyui",
    name: "daisyUI",
    tagline: "Semantic class names for Tailwind, zero JavaScript",
    description:
      "A pure-CSS Tailwind plugin: `btn`, `card`, `modal`. No runtime, no framework binding, works in Rails or Django as happily as in React. Thirty-plus themes ship with it, which makes it unusually good for prototyping.",
    categories: ["component-libraries", "css-styling", "design-systems"],
    tags: ["tailwind-plugin", "no-js", "themes", "css-only"],
    homepage: "https://daisyui.com",
    repo: "https://github.com/saadeghi/daisyui",
    npm: "daisyui",
    docs: "https://daisyui.com/docs/install",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vue", "svelte", "astro", "vanilla"],
      styling: ["tailwind-4", "tailwind-3"],
      react: "any",
      rsc: "safe",
      typescript: false,
      a11y: "partial",
    }),
    color: "#1ad1a5",
    monogram: "DA",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "park-ui",
    name: "Park UI",
    tagline: "Ark UI + Panda CSS, pre-styled and themeable",
    description:
      "Takes Ark's cross-framework primitives and dresses them with Panda CSS recipes, delivered as copy-in source. Effectively shadcn's ownership model applied to a state-machine-based primitive layer.",
    categories: ["component-libraries", "design-systems"],
    tags: ["panda-css", "ark", "copy-paste", "cross-framework"],
    homepage: "https://park-ui.com",
    repo: "https://github.com/cschroeter/park-ui",
    docs: "https://park-ui.com/docs/introduction",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "vue", "solid", "next"],
      styling: ["css-in-js"],
      rsc: "client",
      a11y: "audited",
      install: ["cli", "copy-paste"],
    }),
    color: "#22c55e",
    monogram: "PK",
    featured: false,
    verified: false,
    status: "live",
  },
  {
    kind: "library",
    slug: "flowbite",
    name: "Flowbite",
    tagline: "Tailwind blocks and components across every framework",
    description:
      "A very large catalogue of Tailwind-based components and marketing blocks with React, Vue, Svelte and plain-HTML bindings. The free tier is generous; the paid blocks library is where the real breadth is.",
    categories: ["component-libraries", "blocks-sections", "landing-kits"],
    tags: ["tailwind", "blocks", "marketing", "multi-framework"],
    homepage: "https://flowbite.com",
    repo: "https://github.com/themesberg/flowbite",
    npm: "flowbite",
    docs: "https://flowbite.com/docs/getting-started/introduction",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "freemium",
    priceNote: "Core MIT; Blocks and Pro from $199 one-time",
    stack: stack({
      frameworks: ["react", "vue", "svelte", "next", "vanilla"],
      styling: ["tailwind-4", "tailwind-3"],
      react: "any",
      rsc: "mixed",
      typescript: false,
      a11y: "partial",
      install: ["npm", "cdn", "copy-paste"],
    }),
    color: "#0ea5e9",
    monogram: "FB",
    featured: false,
    verified: false,
    status: "live",
  },

  /* ======================================================================
     MOTION, 3D, EFFECTS
     ====================================================================== */
  {
    kind: "library",
    slug: "motion",
    name: "Motion",
    tagline: "The animation library React reaches for by default",
    description:
      "Declarative animation with a hybrid engine: hardware-accelerated where the browser allows it, JS-driven where it doesn't. Layout animations and shared-element transitions are the features that keep it unrivalled — they are genuinely hard to hand-roll.",
    categories: ["animation-motion", "micro-interactions"],
    tags: ["framer-motion", "spring", "layout-animation", "gestures"],
    homepage: "https://motion.dev",
    repo: "https://github.com/motiondivision/motion",
    npm: "motion",
    docs: "https://motion.dev/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "freemium",
    priceNote: "MIT; Motion+ from $150 one-time for premium examples",
    stack: stack({
      frameworks: ["react", "next", "vue", "vanilla", "vite"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "partial",
    }),
    color: "#ff5c1b",
    monogram: "MO",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "gsap",
    name: "GSAP",
    tagline: "Timeline animation that survives contact with designers",
    description:
      "Twenty years of animation engineering, now fully free including the plugins that used to be paid. Timelines, ScrollTrigger, SplitText and MorphSVG do things no React-first library attempts. Framework-agnostic by design.",
    categories: ["animation-motion", "micro-interactions", "3d-webgl"],
    tags: ["timeline", "scrolltrigger", "svg", "framework-agnostic"],
    homepage: "https://gsap.com",
    repo: "https://github.com/greensock/GSAP",
    npm: "gsap",
    docs: "https://gsap.com/docs/v3",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "free",
    priceNote: "Fully free including all plugins since 2025",
    stack: stack({
      frameworks: ["react", "next", "vue", "svelte", "vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "client",
      a11y: "unknown",
    }),
    color: "#0ae448",
    monogram: "GS",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "magic-ui",
    name: "Magic UI",
    tagline: "150+ animated components for landing pages",
    description:
      "Copy-paste effects — marquees, beams, animated grids, number tickers, shimmer text — built with Motion and Tailwind. Designed as a companion to shadcn/ui rather than a replacement, and it slots in cleanly.",
    categories: ["animation-motion", "blocks-sections", "landing-kits", "micro-interactions"],
    tags: ["shadcn-compatible", "effects", "marketing", "copy-paste"],
    homepage: "https://magicui.design",
    repo: "https://github.com/magicuidesign/magicui",
    docs: "https://magicui.design/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "freemium",
    priceNote: "Components MIT; templates from $99",
    stack: stack({
      frameworks: ["react", "next", "vite"],
      styling: ["tailwind-4", "tailwind-3"],
      rsc: "client",
      a11y: "partial",
      install: ["cli", "copy-paste"],
    }),
    color: "#8b5cf6",
    monogram: "MG",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "aceternity-ui",
    name: "Aceternity UI",
    tagline: "Maximalist effects for sites that want to be noticed",
    description:
      "Spotlight cards, aurora backgrounds, 3D card tilts, infinite moving cards. Visually loud in a way that suits a launch page and suits almost nothing else — which is exactly the job it does well.",
    categories: ["animation-motion", "backgrounds-patterns", "landing-kits", "micro-interactions"],
    tags: ["effects", "tailwind", "motion", "copy-paste"],
    homepage: "https://ui.aceternity.com",
    docs: "https://ui.aceternity.com/components",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "freemium",
    priceNote: "Components free; Pro templates from $99",
    stack: stack({
      frameworks: ["react", "next"],
      styling: ["tailwind-4", "tailwind-3"],
      rsc: "client",
      a11y: "unknown",
      install: ["copy-paste"],
    }),
    color: "#e11d48",
    monogram: "AC",
    featured: false,
    verified: false,
    status: "live",
  },
  {
    kind: "library",
    slug: "motion-primitives",
    name: "Motion Primitives",
    tagline: "Motion components with restraint",
    description:
      "A smaller, quieter set of animated primitives — text effects, transitions, disclosure, cursors — aimed at product UI rather than launch pages. The taste level is noticeably higher than most effect libraries.",
    categories: ["animation-motion", "micro-interactions", "component-libraries"],
    tags: ["motion", "tasteful", "copy-paste", "shadcn-compatible"],
    homepage: "https://motion-primitives.com",
    repo: "https://github.com/ibelick/motion-primitives",
    docs: "https://motion-primitives.com/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "freemium",
    priceNote: "Free tier; Pro blocks from $79",
    stack: stack({
      frameworks: ["react", "next"],
      styling: ["tailwind-4", "tailwind-3"],
      rsc: "client",
      a11y: "partial",
      install: ["cli", "copy-paste"],
    }),
    color: "#0f172a",
    monogram: "MP",
    featured: false,
    verified: false,
    status: "live",
  },
  {
    kind: "library",
    slug: "react-three-fiber",
    name: "React Three Fiber",
    tagline: "Three.js as a React renderer",
    description:
      "Write Three.js scenes as JSX and get reconciliation, hooks and Suspense for free, with no performance penalty over imperative Three. Paired with drei it covers most of what a product 3D scene needs.",
    categories: ["3d-webgl", "animation-motion"],
    tags: ["three", "webgl", "drei", "renderer"],
    homepage: "https://r3f.docs.pmnd.rs",
    repo: "https://github.com/pmndrs/react-three-fiber",
    npm: "@react-three/fiber",
    docs: "https://r3f.docs.pmnd.rs/getting-started/introduction",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vite"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "unknown",
    }),
    color: "#111827",
    monogram: "R3",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "lenis",
    name: "Lenis",
    tagline: "Smooth scroll that doesn't fight the browser",
    description:
      "A tiny scroll normaliser that keeps native scrollbars, accessibility and anchor links intact — the three things every other smooth-scroll library breaks. Pairs naturally with ScrollTrigger.",
    categories: ["animation-motion", "micro-interactions", "performance"],
    tags: ["smooth-scroll", "scroll", "tiny"],
    homepage: "https://lenis.darkroom.engineering",
    repo: "https://github.com/darkroomengineering/lenis",
    npm: "lenis",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vue", "vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "client",
      a11y: "partial",
    }),
    color: "#f59e0b",
    monogram: "LN",
    featured: false,
    verified: false,
    status: "live",
  },

  /* ======================================================================
     DATA: CHARTS, TABLES, FORMS
     ====================================================================== */
  {
    kind: "library",
    slug: "tremor",
    name: "Tremor",
    tagline: "Dashboard components that already look designed",
    description:
      "Charts, KPI cards and tables built for analytics UI specifically, on Recharts and Tailwind. The defaults are close enough to shippable that you spend your time on data rather than on axis formatting.",
    categories: ["charts-dataviz", "dashboard-kits", "component-libraries"],
    tags: ["dashboard", "recharts", "kpi", "analytics"],
    homepage: "https://tremor.so",
    repo: "https://github.com/tremorlabs/tremor",
    npm: "@tremor/react",
    docs: "https://tremor.so/docs/getting-started/installation",
    license: "Apache-2.0",
    licenseBucket: "apache-2.0",
    pricing: "freemium",
    priceNote: "Components Apache 2.0; Blocks from $199",
    stack: stack({
      frameworks: ["react", "next", "vite"],
      styling: ["tailwind-4", "tailwind-3"],
      rsc: "client",
      a11y: "partial",
      install: ["npm", "copy-paste"],
    }),
    color: "#3b82f6",
    monogram: "TR",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "recharts",
    name: "Recharts",
    tagline: "Composable SVG charts, the React way",
    description:
      "Charts assembled from JSX elements rather than configured through an options object, which makes customisation obvious and composition natural. The default choice under most React chart wrappers, shadcn's included.",
    categories: ["charts-dataviz"],
    tags: ["svg", "composable", "d3", "charts"],
    homepage: "https://recharts.org",
    repo: "https://github.com/recharts/recharts",
    npm: "recharts",
    docs: "https://recharts.org/en-US/guide",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vite", "remix"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "partial",
    }),
    color: "#22b5bf",
    monogram: "RC",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "visx",
    name: "visx",
    tagline: "D3 power, React ergonomics, no chart abstraction",
    description:
      "Airbnb's low-level visualisation primitives: scales, shapes, axes and interaction helpers, with no opinion about what a 'chart' is. Steeper than Recharts, and the only sane option when your visualisation is genuinely bespoke.",
    categories: ["charts-dataviz"],
    tags: ["d3", "low-level", "airbnb", "svg"],
    homepage: "https://airbnb.io/visx",
    repo: "https://github.com/airbnb/visx",
    npm: "@visx/visx",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vite"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "unknown",
    }),
    color: "#ff1f5e",
    monogram: "VX",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "tanstack-table",
    name: "TanStack Table",
    tagline: "Headless table logic for any framework",
    description:
      "Sorting, filtering, grouping, pagination, virtualisation and column sizing as pure state — you render every cell yourself. The reason most bespoke data grids no longer need to be written from scratch.",
    categories: ["tables-grids", "headless-primitives"],
    tags: ["headless", "virtualisation", "sorting", "cross-framework"],
    homepage: "https://tanstack.com/table",
    repo: "https://github.com/TanStack/table",
    npm: "@tanstack/react-table",
    docs: "https://tanstack.com/table/latest/docs/introduction",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "vue", "solid", "svelte", "next"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "partial",
    }),
    color: "#ff4154",
    monogram: "TT",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "ag-grid",
    name: "AG Grid",
    tagline: "The data grid you buy when the free ones run out",
    description:
      "Millions of rows, pivoting, Excel export, server-side row models. The community edition is genuinely capable; enterprise is where pivot and integrated charting live. Heavy, and worth it when the requirements are heavy too.",
    categories: ["tables-grids"],
    tags: ["enterprise", "virtualisation", "pivot", "excel"],
    homepage: "https://www.ag-grid.com",
    repo: "https://github.com/ag-grid/ag-grid",
    npm: "ag-grid-react",
    license: "MIT / Commercial",
    licenseBucket: "commercial",
    pricing: "freemium",
    priceNote: "Community MIT; Enterprise from $999/dev",
    stack: stack({
      frameworks: ["react", "angular", "vue", "vanilla", "next"],
      styling: ["vanilla-css"],
      react: "any",
      rsc: "client",
      a11y: "audited",
    }),
    color: "#0e639c",
    monogram: "AG",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "react-hook-form",
    name: "React Hook Form",
    tagline: "Uncontrolled forms, minimal re-renders",
    description:
      "Form state that leans on the DOM instead of re-rendering on every keystroke, with resolvers for Zod, Valibot and friends. The performance difference on large forms is not subtle.",
    categories: ["forms-inputs", "state-management"],
    tags: ["forms", "validation", "zod", "uncontrolled"],
    homepage: "https://react-hook-form.com",
    repo: "https://github.com/react-hook-form/react-hook-form",
    npm: "react-hook-form",
    docs: "https://react-hook-form.com/get-started",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vite", "remix"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "partial",
    }),
    color: "#ec5990",
    monogram: "HF",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "library",
    slug: "zod",
    name: "Zod",
    tagline: "Schema validation with types inferred, not declared",
    description:
      "Declare a schema once and get both runtime validation and the static type. v4 cut bundle size and sped up parsing substantially. The de-facto boundary validator for TypeScript apps.",
    categories: ["forms-inputs", "devtools", "state-management"],
    tags: ["validation", "typescript", "inference", "schema"],
    homepage: "https://zod.dev",
    repo: "https://github.com/colinhacks/zod",
    npm: "zod",
    docs: "https://zod.dev",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vue", "svelte", "vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
    }),
    color: "#3068b7",
    monogram: "ZO",
    featured: false,
    verified: true,
    status: "live",
  },

  /* ======================================================================
     ICONS & ASSETS
     ====================================================================== */
  {
    kind: "resource",
    slug: "lucide",
    name: "Lucide",
    tagline: "1,600+ consistent icons, tree-shakeable",
    description:
      "The community fork of Feather that kept going. One stroke weight, one grid, bindings for every framework, and per-icon imports so you ship only what you use.",
    categories: ["icons"],
    tags: ["icons", "svg", "feather", "tree-shakeable"],
    homepage: "https://lucide.dev",
    repo: "https://github.com/lucide-icons/lucide",
    npm: "lucide-react",
    license: "ISC",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "vue", "svelte", "solid", "vanilla", "next"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "partial",
    }),
    color: "#f56565",
    monogram: "LU",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "resource",
    slug: "phosphor-icons",
    name: "Phosphor Icons",
    tagline: "Nine thousand icons across six weights",
    description:
      "An unusually large family with genuine weight variation — thin through fill — which makes it one of the few sets that can carry an entire product's visual density on its own.",
    categories: ["icons"],
    tags: ["icons", "weights", "svg", "flexible"],
    homepage: "https://phosphoricons.com",
    repo: "https://github.com/phosphor-icons/homepage",
    npm: "@phosphor-icons/react",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "vue", "svelte", "vanilla", "next"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "partial",
    }),
    color: "#0f172a",
    monogram: "PH",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "resource",
    slug: "fontsource",
    name: "Fontsource",
    tagline: "Self-host any open-source font as an npm package",
    description:
      "Every Google Font plus a long tail of others, packaged for npm with subsets and variable-weight files. Removes the third-party request, the layout shift and the privacy footnote in one move.",
    categories: ["fonts-type", "performance"],
    tags: ["fonts", "self-host", "variable-fonts", "privacy"],
    homepage: "https://fontsource.org",
    repo: "https://github.com/fontsource/fontsource",
    npm: "@fontsource-variable/inter",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vue", "svelte", "astro", "vanilla"],
      styling: ["vanilla-css"],
      react: "any",
      rsc: "safe",
      typescript: false,
      a11y: "unknown",
    }),
    color: "#16a34a",
    monogram: "FS",
    featured: false,
    verified: false,
    status: "live",
  },

  /* ======================================================================
     AI TOOLS
     ====================================================================== */
  {
    kind: "tool",
    slug: "v0",
    name: "v0",
    tagline: "Prompt to React, in shadcn's vocabulary",
    description:
      "Vercel's generative UI tool: describe an interface, get working React and Tailwind built on shadcn/ui, then iterate in a live preview. The output is ordinary code you can paste into a repo, which is why it stuck where earlier generators didn't.",
    categories: ["ai-design-tools", "ai-coding-agents", "templates-starters"],
    tags: ["generative-ui", "shadcn", "vercel", "react"],
    homepage: "https://v0.app",
    license: "Commercial",
    licenseBucket: "commercial",
    pricing: "freemium",
    priceNote: "Free tier; Premium from $20/mo",
    stack: stack({
      frameworks: ["react", "next"],
      styling: ["tailwind-4"],
      react: "any",
      rsc: "mixed",
      a11y: "partial",
      install: ["copy-paste"],
    }),
    color: "#0b0b0f",
    monogram: "V0",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "claude-code",
    name: "Claude Code",
    tagline: "An agent that works in your terminal and your repo",
    description:
      "Anthropic's coding agent, available as a CLI, desktop app, web app and IDE extension. Reads and edits the actual repository, runs tests, and drives git — closer to pair programming than to autocomplete.",
    categories: ["ai-coding-agents", "devtools", "agent-frameworks"],
    tags: ["agent", "cli", "anthropic", "mcp"],
    homepage: "https://claude.com/claude-code",
    docs: "https://code.claude.com/docs",
    license: "Commercial",
    licenseBucket: "commercial",
    pricing: "paid",
    priceNote: "Included with Claude Pro and Max plans",
    stack: stack({
      frameworks: ["vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
      install: ["cli"],
    }),
    color: "#d97757",
    monogram: "CC",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "cursor",
    name: "Cursor",
    tagline: "The editor rebuilt around the model",
    description:
      "A VS Code fork where codebase-wide context, multi-file edits and an agent mode are the primary interface rather than a sidebar. The tab-completion model is the part people actually miss when they leave.",
    categories: ["ai-coding-agents", "devtools"],
    tags: ["editor", "vscode", "agent", "autocomplete"],
    homepage: "https://cursor.com",
    license: "Commercial",
    licenseBucket: "commercial",
    pricing: "freemium",
    priceNote: "Hobby free; Pro from $20/mo",
    stack: stack({
      frameworks: ["vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
      install: ["cli"],
    }),
    color: "#0b0b0f",
    monogram: "CU",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "ux-pilot",
    name: "UX Pilot",
    tagline: "AI wireframes and hi-fi designs that sync to Figma",
    description:
      "Generates wireframes and high-fidelity screens from a brief, with design-system awareness, Figma sync and code export. Sits earlier in the process than the code generators — it's a design tool that happens to output code.",
    categories: ["ai-design-tools", "figma-resources", "design-engineering"],
    tags: ["wireframes", "figma", "design-system", "hi-fi"],
    homepage: "https://uxpilot.ai",
    license: "Commercial",
    licenseBucket: "commercial",
    pricing: "freemium",
    priceNote: "Free trial; plans from $19/mo",
    stack: stack({
      frameworks: ["vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
      install: ["cdn"],
    }),
    color: "#c4b5fd",
    monogram: "UX",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "lovable",
    name: "Lovable",
    tagline: "Describe an app, get a deployed full-stack one",
    description:
      "Goes further down the stack than the UI generators — database, auth and deploy included — which makes it strong for prototypes and awkward once a real engineering team needs to take over the repo.",
    categories: ["ai-coding-agents", "no-code", "templates-starters"],
    tags: ["full-stack", "supabase", "prototype", "deploy"],
    homepage: "https://lovable.dev",
    license: "Commercial",
    licenseBucket: "commercial",
    pricing: "freemium",
    priceNote: "Free tier; Pro from $25/mo",
    stack: stack({
      frameworks: ["react", "vite"],
      styling: ["tailwind-3"],
      react: "any",
      rsc: "client",
      a11y: "unknown",
      install: ["cdn"],
    }),
    color: "#ff6b6b",
    monogram: "LV",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "vercel-ai-sdk",
    name: "AI SDK",
    tagline: "One TypeScript API across every model provider",
    description:
      "Unified generation, streaming, tool calling and structured output across providers, plus React hooks for chat and completion UI. Swapping models becomes a config change rather than a rewrite.",
    categories: ["llm-infrastructure", "agent-frameworks"],
    tags: ["streaming", "tool-calling", "providers", "typescript"],
    homepage: "https://ai-sdk.dev",
    repo: "https://github.com/vercel/ai",
    npm: "ai",
    docs: "https://ai-sdk.dev/docs",
    license: "Apache-2.0",
    licenseBucket: "apache-2.0",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "svelte", "vue", "vanilla"],
      styling: ["unstyled"],
      rsc: "mixed",
      a11y: "unknown",
    }),
    color: "#0b0b0f",
    monogram: "AI",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "mastra",
    name: "Mastra",
    tagline: "TypeScript agent framework with workflows and evals",
    description:
      "Agents, deterministic workflow graphs, memory, RAG and evals in one TypeScript package. The workflow primitive is the differentiator — it makes multi-step agents debuggable instead of hopeful.",
    categories: ["agent-frameworks", "evals-observability", "rag-vector"],
    tags: ["agents", "workflows", "evals", "typescript"],
    homepage: "https://mastra.ai",
    repo: "https://github.com/mastra-ai/mastra",
    npm: "@mastra/core",
    docs: "https://mastra.ai/docs",
    license: "Apache-2.0",
    licenseBucket: "apache-2.0",
    pricing: "open-source",
    stack: stack({
      frameworks: ["next", "vanilla", "vite"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
    }),
    color: "#111827",
    monogram: "MA",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "model-context-protocol",
    name: "Model Context Protocol",
    tagline: "The open standard for wiring tools into agents",
    description:
      "A JSON-RPC protocol for exposing tools, resources and prompts to any model client. Write a server once and every MCP-aware agent can use it — the reason a marketplace can be consumed by machines at all.",
    categories: ["agent-frameworks", "devtools"],
    tags: ["mcp", "json-rpc", "standard", "tools"],
    homepage: "https://modelcontextprotocol.io",
    repo: "https://github.com/modelcontextprotocol/servers",
    npm: "@modelcontextprotocol/sdk",
    docs: "https://modelcontextprotocol.io/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["vanilla", "next"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
    }),
    color: "#d97757",
    monogram: "MC",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "Speech synthesis that stopped sounding synthetic",
    description:
      "Text to speech, voice cloning, dubbing and a low-latency streaming API. The quality bar that made voice interfaces viable in consumer products rather than just in demos.",
    categories: ["audio-voice"],
    tags: ["tts", "voice", "dubbing", "streaming"],
    homepage: "https://elevenlabs.io",
    docs: "https://elevenlabs.io/docs",
    license: "Commercial",
    licenseBucket: "commercial",
    pricing: "freemium",
    priceNote: "Free tier; Creator from $22/mo",
    stack: stack({
      frameworks: ["vanilla", "next", "react"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
      install: ["npm", "cdn"],
    }),
    color: "#0b0b0f",
    monogram: "EL",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "fal",
    name: "fal",
    tagline: "Fast inference for generative media models",
    description:
      "Hosted diffusion, video and audio models behind a single API, tuned hard for cold-start and throughput. The place people go when a generative feature has to feel interactive rather than batch.",
    categories: ["image-generation", "video-generation", "llm-infrastructure"],
    tags: ["inference", "diffusion", "video", "api"],
    homepage: "https://fal.ai",
    npm: "@fal-ai/client",
    docs: "https://docs.fal.ai",
    license: "Commercial",
    licenseBucket: "commercial",
    pricing: "paid",
    priceNote: "Usage-based per second of compute",
    stack: stack({
      frameworks: ["next", "react", "vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
    }),
    color: "#7c3aed",
    monogram: "FA",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "langfuse",
    name: "Langfuse",
    tagline: "Open-source tracing and evals for LLM apps",
    description:
      "Traces, prompt management, datasets and scoring for model-backed features, self-hostable end to end. The observability layer you want in place before the first regression, not after.",
    categories: ["evals-observability", "llm-infrastructure", "analytics"],
    tags: ["tracing", "evals", "self-hosted", "prompts"],
    homepage: "https://langfuse.com",
    repo: "https://github.com/langfuse/langfuse",
    npm: "langfuse",
    docs: "https://langfuse.com/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "freemium",
    priceNote: "Self-host free; cloud from $29/mo",
    stack: stack({
      frameworks: ["next", "vanilla", "react"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
    }),
    color: "#0ea5e9",
    monogram: "LF",
    featured: false,
    verified: true,
    status: "live",
  },

  /* ======================================================================
     BUILD
     ====================================================================== */
  {
    kind: "tool",
    slug: "convex",
    name: "Convex",
    tagline: "A reactive database where queries are TypeScript",
    description:
      "Queries and mutations are TypeScript functions, and every query is a live subscription — no cache invalidation layer, no websocket plumbing. Auth, file storage, scheduling and HTTP endpoints come in the same box.",
    categories: ["backends-baas", "databases", "auth"],
    tags: ["realtime", "typescript", "serverless", "reactive"],
    homepage: "https://convex.dev",
    repo: "https://github.com/get-convex/convex-js",
    npm: "convex",
    docs: "https://docs.convex.dev",
    license: "Apache-2.0",
    licenseBucket: "apache-2.0",
    pricing: "freemium",
    priceNote: "Generous free tier; Pro from $25/mo",
    stack: stack({
      frameworks: ["react", "next", "vue", "svelte", "vanilla"],
      styling: ["unstyled"],
      rsc: "mixed",
      a11y: "unknown",
    }),
    color: "#f26522",
    monogram: "CV",
    featured: true,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "tailwindcss",
    name: "Tailwind CSS",
    tagline: "Utility CSS, now with a Rust-speed engine",
    description:
      "v4 replaced the JavaScript config with CSS-native `@theme` and rebuilt the engine in Rust, cutting full builds to milliseconds. Container queries, cascade layers and colour-mix are first-class.",
    categories: ["css-styling", "frameworks", "design-systems"],
    tags: ["utility-css", "oxide", "design-tokens", "v4"],
    homepage: "https://tailwindcss.com",
    repo: "https://github.com/tailwindlabs/tailwindcss",
    npm: "tailwindcss",
    docs: "https://tailwindcss.com/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vue", "svelte", "astro", "vanilla"],
      styling: ["tailwind-4"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
    }),
    color: "#38bdf8",
    monogram: "TW",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "clerk",
    name: "Clerk",
    tagline: "Auth with UI components that don't look bolted on",
    description:
      "Sessions, organisations, passkeys and MFA behind drop-in React components that are actually themeable. Removes weeks of account-management UI that nobody wants to build twice.",
    categories: ["auth", "backends-baas", "component-libraries"],
    tags: ["passkeys", "organizations", "components", "sessions"],
    homepage: "https://clerk.com",
    npm: "@clerk/nextjs",
    docs: "https://clerk.com/docs",
    license: "Commercial",
    licenseBucket: "commercial",
    pricing: "freemium",
    priceNote: "Free to 10k MAU; Pro from $25/mo",
    stack: stack({
      frameworks: ["react", "next", "remix", "vue", "astro"],
      styling: ["css-in-js"],
      rsc: "mixed",
      a11y: "audited",
    }),
    color: "#6c47ff",
    monogram: "CL",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "supabase",
    name: "Supabase",
    tagline: "Postgres with the rest of the backend attached",
    description:
      "A real Postgres database plus auth, storage, realtime, edge functions and vector search, all open source and self-hostable. Row-level security is the load-bearing feature and the main learning curve.",
    categories: ["databases", "backends-baas", "auth", "rag-vector"],
    tags: ["postgres", "rls", "realtime", "pgvector"],
    homepage: "https://supabase.com",
    repo: "https://github.com/supabase/supabase",
    npm: "@supabase/supabase-js",
    docs: "https://supabase.com/docs",
    license: "Apache-2.0",
    licenseBucket: "apache-2.0",
    pricing: "freemium",
    priceNote: "Free tier; Pro from $25/mo",
    stack: stack({
      frameworks: ["react", "next", "vue", "svelte", "vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "mixed",
      a11y: "unknown",
    }),
    color: "#3ecf8e",
    monogram: "SB",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "storybook",
    name: "Storybook",
    tagline: "The workshop where components get built in isolation",
    description:
      "Develop, document and test components outside the app. Interaction tests, accessibility checks and visual regression all hang off the same stories, which is what makes the setup cost pay back.",
    categories: ["documentation", "testing", "design-engineering", "devtools"],
    tags: ["stories", "isolation", "visual-testing", "docs"],
    homepage: "https://storybook.js.org",
    repo: "https://github.com/storybookjs/storybook",
    npm: "storybook",
    docs: "https://storybook.js.org/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "vue", "svelte", "angular", "next", "vite"],
      styling: ["unstyled"],
      react: "any",
      rsc: "client",
      a11y: "audited",
    }),
    color: "#ff4785",
    monogram: "SB",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "playwright",
    name: "Playwright",
    tagline: "End-to-end tests that are stubbornly reliable",
    description:
      "Auto-waiting, trace viewer, and real Chromium, Firefox and WebKit. The auto-wait design is why Playwright suites tend not to rot into a wall of arbitrary sleeps.",
    categories: ["testing", "devtools", "accessibility"],
    tags: ["e2e", "browser", "trace-viewer", "cross-browser"],
    homepage: "https://playwright.dev",
    repo: "https://github.com/microsoft/playwright",
    npm: "@playwright/test",
    docs: "https://playwright.dev/docs/intro",
    license: "Apache-2.0",
    licenseBucket: "apache-2.0",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vue", "svelte", "vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "audited",
    }),
    color: "#2ead33",
    monogram: "PW",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "posthog",
    name: "PostHog",
    tagline: "Product analytics, replays and flags in one place",
    description:
      "Events, session replay, feature flags, experiments and surveys, self-hostable and open source. Consolidates four subscriptions into one, at the cost of a heavier client bundle.",
    categories: ["analytics", "devtools", "evals-observability"],
    tags: ["events", "replay", "feature-flags", "self-hosted"],
    homepage: "https://posthog.com",
    repo: "https://github.com/PostHog/posthog",
    npm: "posthog-js",
    docs: "https://posthog.com/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "freemium",
    priceNote: "Generous free tier, then usage-based",
    stack: stack({
      frameworks: ["react", "next", "vue", "vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "client",
      a11y: "unknown",
    }),
    color: "#f54e00",
    monogram: "PH",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "resend",
    name: "Resend",
    tagline: "Transactional email you write as React",
    description:
      "An email API from the people behind React Email, so templates are components rather than table soup. Deliverability tooling and a genuinely pleasant DX for the least pleasant part of the stack.",
    categories: ["email-messaging", "email-templates"],
    tags: ["transactional", "react-email", "deliverability"],
    homepage: "https://resend.com",
    npm: "resend",
    docs: "https://resend.com/docs",
    license: "Commercial",
    licenseBucket: "commercial",
    pricing: "freemium",
    priceNote: "3k emails/mo free; Pro from $20/mo",
    stack: stack({
      frameworks: ["react", "next", "vanilla"],
      styling: ["css-in-js"],
      rsc: "safe",
      a11y: "partial",
    }),
    color: "#0b0b0f",
    monogram: "RS",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "typesense",
    name: "Typesense",
    tagline: "Typo-tolerant search you can actually self-host",
    description:
      "An open-source search engine tuned for instant, typo-tolerant results with sane defaults, plus vector and hybrid search. The pragmatic middle ground between Elasticsearch's weight and Algolia's bill.",
    categories: ["search", "databases", "rag-vector"],
    tags: ["search", "typo-tolerance", "vector", "self-hosted"],
    homepage: "https://typesense.org",
    repo: "https://github.com/typesense/typesense",
    npm: "typesense",
    docs: "https://typesense.org/docs",
    license: "GPL-3.0",
    licenseBucket: "gpl",
    pricing: "freemium",
    priceNote: "Self-host free (GPL); Cloud from $19/mo",
    stack: stack({
      frameworks: ["react", "next", "vue", "vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      a11y: "unknown",
    }),
    color: "#d52d5c",
    monogram: "TS",
    featured: false,
    verified: false,
    status: "live",
  },
  {
    kind: "tool",
    slug: "payload",
    name: "Payload",
    tagline: "A CMS that installs into your Next.js app",
    description:
      "TypeScript-first, code-defined collections, and an admin panel that mounts inside your own Next app rather than living on someone else's domain. Owning the database is the whole pitch.",
    categories: ["cms", "backends-baas", "databases"],
    tags: ["headless-cms", "nextjs", "typescript", "self-hosted"],
    homepage: "https://payloadcms.com",
    repo: "https://github.com/payloadcms/payload",
    npm: "payload",
    docs: "https://payloadcms.com/docs",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "freemium",
    priceNote: "Self-host free; Cloud from $35/mo",
    stack: stack({
      frameworks: ["next", "react"],
      styling: ["css-modules"],
      rsc: "mixed",
      a11y: "partial",
    }),
    color: "#0b0b0f",
    monogram: "PL",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "tool",
    slug: "zustand",
    name: "Zustand",
    tagline: "State management that fits in your head",
    description:
      "A store in a hook, no provider, no boilerplate, and selectors that keep re-renders narrow. Small enough that reaching for it rarely needs a justification meeting.",
    categories: ["state-management"],
    tags: ["store", "hooks", "tiny", "no-provider"],
    homepage: "https://zustand.docs.pmnd.rs",
    repo: "https://github.com/pmndrs/zustand",
    npm: "zustand",
    license: "MIT",
    licenseBucket: "mit",
    pricing: "open-source",
    stack: stack({
      frameworks: ["react", "next", "vite", "remix"],
      styling: ["unstyled"],
      rsc: "client",
      a11y: "unknown",
    }),
    color: "#7c3aed",
    monogram: "ZU",
    featured: false,
    verified: true,
    status: "live",
  },
  {
    kind: "resource",
    slug: "wcag-patterns",
    name: "ARIA Authoring Practices",
    tagline: "The reference implementation for every widget pattern",
    description:
      "W3C's worked examples for accordions, comboboxes, grids and the rest — keyboard maps, ARIA roles and live demos. The document every accessible component library is quietly checked against, including this one.",
    categories: ["accessibility", "documentation", "design-engineering"],
    tags: ["wai-aria", "keyboard", "patterns", "w3c"],
    homepage: "https://www.w3.org/WAI/ARIA/apg",
    license: "W3C Document License",
    licenseBucket: "free-personal",
    pricing: "free",
    stack: stack({
      frameworks: ["vanilla"],
      styling: ["unstyled"],
      react: "any",
      rsc: "safe",
      typescript: false,
      a11y: "audited",
      install: ["copy-paste"],
    }),
    color: "#005a9c",
    monogram: "AP",
    featured: false,
    verified: true,
    status: "live",
  },

];

export const baseListings: Listing[] = raw.map(hydrate);
